src/objects/Apppage__c.object
<CustomObject>
    <description>Actual pages for mobile app. This is where springboards launch from.

Use attachments to associate an image with the page</description>
    <fields>
        <fullName>DemoApp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DemoApp</label>
        <referenceTo>DemoApp__c</referenceTo>
        <relationshipLabel>App Pages</relationshipLabel>
        <relationshipName>App_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>App Page</label>
    <nameField>
        <displayFormat>AP-{0000}</displayFormat>
        <label>Apppage Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DemoApp__c.object
<CustomObject>
    <description>Uber grouping of a demo app which is a collection of showcases and apppages</description>
    <label>DemoApp</label>
    <nameField>
        <label>DemoApp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DemoApps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Showcase__c.object
<CustomObject>
    <description>Customer showcase information.

Customer use case images should be added as attachments.</description>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <description>Customer name to be displayed in app</description>
        <label>Customer Name</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DemoApp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DemoApp</label>
        <referenceTo>DemoApp__c</referenceTo>
        <relationshipLabel>Showcases</relationshipLabel>
        <relationshipName>Showcases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Case_Description__c</fullName>
        <description>Short, single paragraph description of the customers use case and story</description>
        <label>Use Case Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Showcase</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Showcase Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Showcases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Springboard__c.object
<CustomObject>
    <description>Springboards are the action hooks for separate functions (Visualforce) features that get &apos;pulled&apos; into the mobile demo app</description>
    <fields>
        <fullName>Action_Name__c</fullName>
        <description>The name of the action that will appear on the rendered button</description>
        <inlineHelpText>The name of the action that will appear on the rendered button</inlineHelpText>
        <label>Action Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visualforce_Page_Name__c</fullName>
        <description>The visualforce page that will form the link from the button that gets clicked. Don&apos;t use any slashes.</description>
        <inlineHelpText>The visualforce page that will form the link from the button that gets clicked. Don&apos;t use any slashes.</inlineHelpText>
        <label>Visualforce Page Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Springboard</label>
    <nameField>
        <displayFormat>SB-{0000}</displayFormat>
        <label>Springboard Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Springboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Springboard_Pages__c.object
<CustomObject>
    <description>The many-to-many junction object to allow a springboard to appear on multiple app pages, or customer showcase pages</description>
    <fields>
        <fullName>App_Page__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>App Page</label>
        <referenceTo>Apppage__c</referenceTo>
        <relationshipLabel>Springboard Pages</relationshipLabel>
        <relationshipName>Springboard_Pages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Showcase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Showcase</label>
        <referenceTo>Showcase__c</referenceTo>
        <relationshipLabel>Springboard Pages</relationshipLabel>
        <relationshipName>Springboard_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Springboard__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Springboard</label>
        <referenceTo>Springboard__c</referenceTo>
        <relationshipLabel>Springboard Pages</relationshipLabel>
        <relationshipName>Springboard_Pages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Springboard Pages</label>
    <nameField>
        <displayFormat>SBP-{0000}</displayFormat>
        <label>Springboard Pages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Springboard Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MobileDemoAppController.cls
public with sharing class MobileDemoAppController {
	public static List<Showcase__c> showcases {get;set;}

	public MobileDemoAppController(ApexPages.StandardController controller) {}

	@RemoteAction
	public static List<Showcase__c> getShowcases(String appId) {
		String queryString = 'SELECT id, Customer_Name__c, Use_Case_Description__c, (SELECT id FROM attachments) FROM Showcase__c WHERE DemoApp__c = \''+appId+'\' ORDER BY name ASC';
		showcases = Database.query(queryString);

		return showcases;
	}

	@RemoteAction
	public static List<AppPageSpringboard> getAppPages(String appId) {
		List<AppPageSpringboard> aps = new List<AppPageSpringboard>();
		String queryString = 'SELECT id, Title__c, Description__c FROM Apppage__c WHERE DemoApp__c = \''+appId+'\' ORDER BY name ASC';
		List<Apppage__c> appPages = Database.query(queryString);

		for (AppPage__c ap: appPages) {
			aps.add(new AppPageSpringboard(ap));
		}

		return aps;
	}

	public class AppPageSpringboard {
		Apppage__c appPage;
		List<Springboard_Pages__c> springboards;

		public AppPageSpringboard(Apppage__c ap) {
			appPage = ap;
			springboards = [SELECT Springboard__r.Action_Name__c, Springboard__r.Visualforce_Page_Name__c FROM Springboard_Pages__c WHERE App_Page__c =: appPage.id];
		}
	}
}