src/objects/Property_Inspection__c.object
<CustomObject>
    <fields>
        <fullName>City_Address__c</fullName>
        <label>City Address</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>State_Address__c</fullName>
        <label>State Address</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Address__c</fullName>
        <label>Zip Address</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property Inspection</label>
    <nameField>
        <displayFormat>INS-{0000}</displayFormat>
        <label>Property Inspection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PropertyInspectionController.cls
global with sharing class PropertyInspectionController{    
  
    public PropertyInspectionController() {} 
        
    @RemoteAction
    global static string addPropertyPicture(string imageData, String recordId) {
        
        //Add the picture as an Attachment to the InspectionReport record
        Attachment a = new Attachment (ParentId = recordId,
                                       Body = EncodingUtil.base64Decode(imageData),                                        
                                       ContentType = 'image/jpg',
                                       Name = 'PropertyPhoto');
        insert a;  
         
        return a.Id;    
    }
 
    @RemoteAction  
    global static String saveInspectionReport(String street, String city, String state, String zip, String description, Decimal lat, Decimal lng) {  
         
        Property_Inspection__c pi = new Property_Inspection__c();
        pi.Street_Address__c = street;    
        pi.City_Address__c = city;
        pi.State_Address__c = state;
        pi.Zip_Address__c = zip;
        pi.Description__c = description;
        pi.Property_Location__Latitude__s = lat;
        pi.Property_Location__Longitude__s = lng;
        insert pi;
        
        return pi.Id;
                   
    }  
}